server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://YOUR_AUTH0_DOMAIN/
#          audience: YOUR_API_IDENTIFIER
#

logging:
  level:
    root: INFO

